// SOURCE: https://www.toptal.com/developers/keycode/table-of-all-keycodes
export type KeyCodes =
  | "Delete"
  | "Backspace"
  | "Tab"
  | "Enter"
  | "ShiftLeft"
  | "ControlLeft"
  | "AltLeft"
  | "CapsLock"
  | "Escape"
  | "Space"
  | "ArrowLeft"
  | "ArrowUp"
  | "ArrowRight"
  | "ArrowDown"
  | "Digit0"
  | "Digit1"
  | "Digit2"
  | "Digit3"
  | "Digit4"
  | "Digit5"
  | "Digit6"
  | "Digit7"
  | "Digit8"
  | "Digit9"
  | "Period"
  | "Semicolon"
  | "Backquote"
  | "Equal"
  | "Minus"
  | "KeyA"
  | "KeyB"
  | "KeyC"
  | "KeyD"
  | "KeyE"
  | "KeyF"
  | "KeyG"
  | "KeyH"
  | "KeyI"
  | "KeyJ"
  | "KeyK"
  | "KeyL"
  | "KeyM"
  | "KeyN"
  | "KeyO"
  | "KeyP"
  | "KeyQ"
  | "KeyR"
  | "KeyS"
  | "KeyT"
  | "KeyU"
  | "KeyV"
  | "KeyW"
  | "KeyX"
  | "KeyY"
  | "KeyZ"
  | "MetaLeft"
  | "MetaRight"
  | "ContextMenu"
  | "F1"
  | "F2"
  | "F3"
  | "F4"
  | "F5"
  | "F6"
  | "F7"
  | "F8"
  | "F9"
  | "F10"
  | "F11"
  | "F12"
  | "BracketLeft"
  | "BracketRight"
  | "Backquote"
  | "Backslash"
  | "Minus"
  | "Backslash"
  | "BracketRight"
  | "Minus"
  | "Semicolon"
  | "Equal"
  | "Comma"
  | "Minus"
  | "Period"
  | "Slash"
  | "Backquote"
  | "NumpadComma"
  | "BracketLeft"
  | "Backslash"
  | "BracketRight"
  | "Backquote"
  | "AltRight";

export const KeyCodeToVisualKey: Record<KeyCodes, string> = {
  Delete: "Supr",
  Backspace: "⌫",
  Tab: "↹",
  Enter: "↵",
  ShiftLeft: "⇧",
  ControlLeft: "Ctrl",
  AltLeft: "Alt",
  CapsLock: "⇪",
  Escape: "⎋",
  Space: "",
  ArrowLeft: "←",
  ArrowUp: "↑",
  ArrowRight: "→",
  ArrowDown: "↓",
  Digit0: "0",
  Digit1: "1",
  Digit2: "2",
  Digit3: "3",
  Digit4: "4",
  Digit5: "5",
  Digit6: "6",
  Digit7: "7",
  Digit8: "8",
  Digit9: "9",
  Period: ":",
  Semicolon: ";",
  Backquote: "<",
  Equal: "=",
  Minus: "-",
  KeyA: "A",
  KeyB: "B",
  KeyC: "C",
  KeyD: "D",
  KeyE: "E",
  KeyF: "F",
  KeyG: "G",
  KeyH: "H",
  KeyI: "I",
  KeyJ: "J",
  KeyK: "K",
  KeyL: "L",
  KeyM: "M",
  KeyN: "N",
  KeyO: "O",
  KeyP: "P",
  KeyQ: "Q",
  KeyR: "R",
  KeyS: "S",
  KeyT: "T",
  KeyU: "U",
  KeyV: "V",
  KeyW: "W",
  KeyX: "X",
  KeyY: "Y",
  KeyZ: "Z",
  MetaLeft: "⌘",
  MetaRight: "⌘",
  ContextMenu: "▤",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  BracketLeft: "[",
  BracketRight: "]",
  Backslash: "$",
  Comma: ",",
  Slash: "/",
  NumpadComma: ".",
  AltRight: "Alt",
};
